import { Button } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function Home({ setMode, mode }) {


  return (
    <div className="p-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen px-0 py-2 flex   items-center flex-1 flex-col dark:bg-slate-800">
        {/* <div className="flex justify-end  w-full pr-10">
         
        </div> */}
        <h1 className='m-0 dark:text-white text-[4rem] items-center'>
          Welcome to  <a href="https://nextjs.org" className=" text-black hover:text-blue-500 dark:text-blue-500  dark:hover:text-red-500 no-underline hover:underline">Next.js!</a>
        </h1>

        <p className="items-center my-[4rem] mx-0 text-2xl dark:text-white">
          Get started by editing{' '}
          <code className=" bg-slate-100 rounded-[5px] p-3 text-sm font-mono dark:text-black">pages/index.js</code>
        </p>

        <div className="flex justify-center items-center flex-wrap max-w-[800px] sm:w-full sm:flex-col ">
          <a href="https://nextjs.org/docs" className="m-4 p-4 items-center max-w-[300px] text-inherit rounded-lg border-1 border-solid border-slate-300 hover:border-blue-500  ">
            <h2 className="mt-0 mr-0 mb-4 ml-0  text-2xl leading-6 dark:text-white">Documentation &rarr;</h2>
            <p className="m-0 text-md font-medium leading-6 dark:text-white">Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="m-4 p-4 items-center max-w-[300px] text-inherit rounded-lg border-1 border-solid border-slate-300 hover:border-blue-500  ">
            <h2 className="mt-0 mr-0 mb-4 ml-0  text-2xl leading-6 dark:text-white">Learn &rarr;</h2>
            <p className="m-0 text-md font-medium leading-6 dark:text-white">Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className="m-4 p-4 items-center max-w-[300px] text-inherit rounded-lg border-1 border-solid border-slate-300 hover:border-blue-500  "
          >
            <h2 className="mt-0 mr-0 mb-4 ml-0  text-2xl leading-6 dark:text-white">Examples &rarr;</h2>
            <p className="m-0 text-md font-medium leading-6 dark:text-white">Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="m-4 p-4 items-center max-w-[300px] text-inherit rounded-lg border-1 border-solid border-slate-300 hover:border-blue-500  "
          >
            <h2 className="mt-0 mr-0 mb-4 ml-0  text-2xl leading-6 dark:text-white">Deploy &rarr;</h2>
            <p className="m-0 text-md font-medium leading-6 dark:text-white">
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
